baseurl = "https://www.osgi.org/"
DefaultContentLanguage = "en"
title = "OSGi Working Group"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = []
themesDir = "node_modules/"
enableRobotsTXT = true
pluralizeListTitles = false

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "The OSGi Working Group is a worldwide consortium of technology innovators that advances a proven and mature process to create open specifications that enable the modular assembly of software built with Java technology. Modularity reduces software complexity; OSGi is the best model to modularize Java."
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["eclipse osgi", "osgi", "open source osgi", "dynamic module system", "java module"]
  gcse = "011805775785170369411:p3ec0igo0qq"
  js = "js/solstice.js"
  logo = "images/logo/osgi.png"
  styles = "css/styles.css"
  favicon = "images/favicon.ico"
# share_img = ""
# header_wrapper_class = ""
# logo_width = ""
# header_left_classes = ""
# main_menu_wrapper_classes = ""
  featured_content_publish_target = "osgi"
#  call_for_action_text = "Download"
#  call_for_action_url = "//www.eclipse.org/downloads/"
#  call_for_action_icon = "fa-download"
  twitter_url = "https://twitter.com/OSGiWG"
  linkedin_url = "https://www.linkedin.com/groups/122461/"
  youtube_url = "https://www.youtube.com/channel/UC2OOgfzdAv-yZsvvCKwzAow"

[taxonomies]
  category = "categories"
  tag = "tags"
  membership_level = "membership_levels"
  participation_level = "participation_levels"

[Author]
  name = "OSGi Working Group"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  twitter = "OSGiWG"
  linkedin = "groups/122461/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 1
 
[[menu.main]]
  name = "About Us"
  parent = "About"
  url = "/about"
  weight = 1
  
[[menu.main]]
  name = "FAQ"
  parent = "About"
  url = "/about/faq"
  weight = 2

[[menu.sidebar]]
  name = "About"
  url = "/about"
  weight = 2
  identifier = "about"
  
[[menu.sidebar]]
  parent ="about"
  name = "About Us"
  url = "/about"
  pre = "<i data-feather=\"users\"></i>" # https://feathericons.com/
  weight = 1
  
[[menu.sidebar]]
  parent ="about"
  name = "FAQ"
  url = "/about/faq"
  pre = "<i data-feather=\"help-circle\"></i>" # https://feathericons.com/
  weight = 2

[[menu.main]]
  name = "Members"
  url = "/membership"
  weight = 1

[[menu.main]]
  name = "Resources"
  url = "/resources"
  weight = 1
 
[[menu.main]]
  name = "Documentation"
  parent = "Resources"
  url = "https://docs.osgi.org/"
  weight = 1
 
[[menu.main]]
  name = "Specification Project"
  parent = "Resources"
  url = "https://projects.eclipse.org/projects/technology.osgi"
  weight = 1

[[menu.main]]
  name = "Technology Project"
  parent = "Resources"
  url = "https://projects.eclipse.org/projects/technology.osgi-technology"
  weight = 1

[[menu.main]]
  name = "What is OSGi?"
  parent = "Resources"
  url = "/resources/what-is-osgi"
  weight = 2
 
[[menu.main]]
  name = "Modularity"
  parent = "Resources"
  url = "/resources/modularity"
  weight = 2
 
[[menu.main]]
  name = "Complexity, Modularity and Business"
  parent = "Resources"
  url = "/resources/complexity-modularity-and-business"
  weight = 2
 
[[menu.main]]
  name = "Where to Start"
  parent = "Resources"
  url = "/resources/where-to-start"
  weight = 2
 
[[menu.main]]
  name = "Architecture"
  parent = "Resources"
  url = "/resources/architecture"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "https://blog.osgi.org/"
  weight = 2
