[build]
publish = "public"
command = "npm run production && hugo --gc --minify -b https://www.osgi.org"

[build.environment]
NODE_VERSION = "12.18.3"

[context.production.environment]
HUGO_VERSION = "0.76.5"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm run production && hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.76.5"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run production && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.76.5"

[context.branch-deploy]
command = "npm run production && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.76.5"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/xmlns/*"
  to = "https://docs.osgi.org/xmlns/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "/javadoc/*"
  to = "https://docs.osgi.org/javadoc/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "/specification/*"
  to = "https://docs.osgi.org/specification/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "/download/*"
  to = "https://docs.osgi.org/download/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
